on:
  schedule:
    # Adjust the cron schedule as needed.
    # Runs "At every 10th minute." (https://crontab.guru/#*/10_*_*_*_*)
    - cron: "*/10 * * * *"
env:
  POLYTOMIC_API_KEY: ${{ secrets.POLYTOMIC_API_KEY }}

jobs:
  pull-request:
    environment: exporter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create output directory
        run: |
          mkdir -p terraform
      - name: Polytomic Terraform Sync
        uses: polytomic/terraform-export-gh-action@v0.0.9
        with:
          api_key: ${{ env.POLYTOMIC_API_KEY }}

      # Create a pull request with the changes.
      # Comment this step out if you want to commit the changes directly to the default branch.
      # See the "Commit changes" step below.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Sync terraform
          title: Polytomic Terraform Sync
          body: |
            This is a pull request by [polytomic](https://polytomic.com) to sync terraform configuration.
            _Auto-generated by polytomic terraform sync_
          # This is the branch that will be used to create the pull request.
          # It will be created if it doesn't already exist.
          # The default value is "polytomic-terraform".
          branch: polytomic-terraform

      # Uncomment the following steps if you want to commit the changes directly to the default branch.
      # Comment out the "Create Pull Request" step above.
      # This will commit the changes directly to the default branch. Use with caution.
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
